"""Domain library (RFC 0001, P10) — pure, no side effects.

Loads the bundle once, runs detectors and validates documents/relations,
returning structured ``Detection``/``Violation`` objects. **Nothing here
writes files, calls ``sys.exit()`` or knows about GitHub Actions** — the CLI
presents these results and derived artifacts are generated by a separate
command. The bidirectional check (P14.6) operates on detection
``fingerprint``s, never on set-equality with ``regras_afetadas``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from achado_schema import load_achados, validate_bundle_achados
from detections import Violation
from detectors import ALL as ALL_DETECTORS
from okf_common import BundleIntegrityError
from okf_to_csv import parse_doc, validate_bundle_identity
from regra_schema import ADMIN_FIELD_DEFAULTS

if TYPE_CHECKING:
    from pathlib import Path

    from achado_schema import Achado
    from detections import Detection


@dataclass(frozen=True)
class Regra:
    """One regra doc, parsed — its frontmatter and body sections."""

    id: str
    frontmatter: dict
    sections: dict[str, str]

    @property
    def status_regra(self) -> str:
        """Administrative state; defaults to 'ativa' when the field is absent (P2.1)."""
        return str(self.frontmatter.get("status_regra") or ADMIN_FIELD_DEFAULTS["status_regra"])


@dataclass(frozen=True)
class Bundle:
    """A loaded bundle: its directory, regras and achados."""

    bundle_dir: Path
    regras: tuple[Regra, ...]
    achados: tuple[Achado, ...]

    @classmethod
    def load(cls, bundle_dir: Path) -> Bundle:
        """Read every regra and achado doc under ``bundle_dir`` (read-only)."""
        regras = []
        for doc_path in sorted((bundle_dir / "regras").glob("regra-*.md")):
            frontmatter, sections = parse_doc(doc_path.read_text(encoding="utf-8"))
            regras.append(Regra(id=doc_path.stem, frontmatter=frontmatter, sections=sections))
        return cls(bundle_dir=bundle_dir, regras=tuple(regras), achados=tuple(load_achados(bundle_dir)))

    def active_regras(self) -> list[Regra]:
        """Only regras with ``status_regra: ativa`` (the ones detectors compare)."""
        return [r for r in self.regras if r.status_regra == "ativa"]

    def regra_ids(self) -> frozenset[str]:
        """Every regra id present in the bundle."""
        return frozenset(r.id for r in self.regras)

    def open_achados(self) -> list[Achado]:
        """Only achados with ``situacao: aberto``."""
        return [a for a in self.achados if a.situacao == "aberto"]


def collect_detections(bundle: Bundle) -> list[Detection]:
    """Run every registered detector and return all mechanical occurrences."""
    detections: list[Detection] = []
    for detector in ALL_DETECTORS:
        detections.extend(detector.detect(bundle))
    return detections


def _open_fingerprints(bundle: Bundle) -> dict[str, list[Achado]]:
    """Map each fingerprint referenced by an open achado to the achados claiming it."""
    fp_to_achados: dict[str, list[Achado]] = {}
    for achado in bundle.open_achados():
        for fp in achado.fingerprints:
            fp_to_achados.setdefault(fp, []).append(achado)
    return fp_to_achados


def uncovered_detections(bundle: Bundle, detections: list[Detection] | None = None) -> list[Detection]:
    """Current detections that no open achado references by fingerprint (P14_DETECCAO_SEM_ACHADO)."""
    detections = collect_detections(bundle) if detections is None else detections
    covered = _open_fingerprints(bundle)
    return [d for d in detections if d.fingerprint not in covered]


def stale_detection_refs(bundle: Bundle, detections: list[Detection] | None = None) -> list[Achado]:
    """Open achados whose fingerprints the detectors no longer emit (P14_ACHADO_SEM_DETECCAO)."""
    detections = collect_detections(bundle) if detections is None else detections
    current = {d.fingerprint for d in detections}
    return [
        achado
        for achado in bundle.open_achados()
        if achado.fingerprints and not set(achado.fingerprints) <= current
    ]


def _check_structural(bundle: Bundle) -> list[Violation]:
    """Camada 1: regra sequence identity + achado schema. Both bloqueante."""
    violations: list[Violation] = []
    try:
        validate_bundle_identity(bundle.bundle_dir)
    except BundleIntegrityError as exc:
        violations.append(Violation("P_ESTRUTURA_REGRAS", str(exc)))
    violations.extend(
        Violation("P14_ACHADO_INVALIDO", error)
        for error in validate_bundle_achados(bundle.bundle_dir, known_regra_ids=bundle.regra_ids())
    )
    return violations


def _check_bidirectional(bundle: Bundle, detections: list[Detection]) -> list[Violation]:
    """Camada 2: detections <-> open achados must agree, over fingerprints (P14.6)."""
    fp_to_achados = _open_fingerprints(bundle)

    sem_achado = [
        Violation(
            "P14_DETECCAO_SEM_ACHADO",
            f"{detection.detector} detected {sorted(detection.regras)} "
            f"(fingerprint {detection.fingerprint}) with no open achado",
        )
        for detection in uncovered_detections(bundle, detections)
    ]
    sem_deteccao = [
        Violation(
            "P14_ACHADO_SEM_DETECCAO",
            f"{achado.doc_id} references a detection no longer emitted — resolve it or update its deteccoes",
        )
        for achado in stale_detection_refs(bundle, detections)
    ]
    duplicada = [
        Violation(
            "P14_DETECCAO_DUPLICADA",
            f"detection {fingerprint} is claimed by more than one open achado "
            f"({', '.join(a.doc_id for a in achados)}) without an explicit relation",
        )
        for fingerprint, achados in fp_to_achados.items()
        if len(achados) > 1
    ]
    return [*sem_achado, *sem_deteccao, *duplicada]


def validate_bundle(bundle: Bundle) -> list[Violation]:
    """Every blocking check (P10 camadas 1-2). Returns all violations (empty = clean)."""
    detections = collect_detections(bundle)
    return [*_check_structural(bundle), *_check_bidirectional(bundle, detections)]
